"""auto-generated pre-deploy migration

Revision ID: ef8f6e149d94
Revises: 52855424a227
Create Date: 2026-04-09 11:34:28.821207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8f6e149d94'
down_revision: Union[str, None] = '52855424a227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_magic_token')
        batch_op.create_index(batch_op.f('ix_users_magic_login_token'), ['magic_login_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_magic_login_token'))
        batch_op.create_index('idx_users_magic_token', ['magic_login_token'], unique=True)

    # ### end Alembic commands ###
