"""Initial migration

Revision ID: 70a2a0305844
Revises: 
Create Date: 2026-03-27 23:26:39.232647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a2a0305844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jackpots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('dc_level', sa.Integer(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_tiers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tier_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_2wk', sa.Integer(), nullable=False),
    sa.Column('price_4wk', sa.Integer(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('popular', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tier_id')
    )
    op.create_table('tips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fixture_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('league', sa.String(length=255), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('prediction', sa.String(length=255), nullable=False),
    sa.Column('odds', sa.String(length=50), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('bookmaker_odds', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_premium', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tips_fixture_id'), 'tips', ['fixture_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_id', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('jackpot_purchases',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jackpot_id', sa.BigInteger(), nullable=False),
    sa.Column('payment_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jackpot_id'], ['jackpots.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jackpot_purchases_jackpot_id'), 'jackpot_purchases', ['jackpot_id'], unique=False)
    op.create_index(op.f('ix_jackpot_purchases_user_id'), 'jackpot_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jackpot_purchases_user_id'), table_name='jackpot_purchases')
    op.drop_index(op.f('ix_jackpot_purchases_jackpot_id'), table_name='jackpot_purchases')
    op.drop_table('jackpot_purchases')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tips_fixture_id'), table_name='tips')
    op.drop_table('tips')
    op.drop_table('subscription_tiers')
    op.drop_table('jackpots')
    # ### end Alembic commands ###
