"""Security & Referral Models

Revision ID: 79101d3ef2bd
Revises: 1bbd7413fa87
Create Date: 2026-04-02 18:34:42.033631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79101d3ef2bd'
down_revision: Union[str, None] = '1bbd7413fa87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referrer_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('referrals_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_session_id'), ['session_id'], unique=True)
        batch_op.create_foreign_key('fk_users_referrer_id', 'users', ['referrer_id'], ['id'])

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_referrer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_session_id'))
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_column('referrals_count')
        batch_op.drop_column('referrer_id')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('session_id')
        batch_op.drop_column('profile_picture')
        
    pass

    # ### end Alembic commands ###
