"""add favorite teams

Revision ID: eb4720b7f44b
Revises: 70a2a0305844
Create Date: 2026-03-30 11:52:08.340725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4720b7f44b'
down_revision: Union[str, None] = '70a2a0305844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_teams', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_teams')
    # ### end Alembic commands ###
