"""Add Geo-Fair Pricing

Revision ID: 5ddc197b0f77
Revises: 4c8bd011c095
Create Date: 2026-04-01 22:45:41.665251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ddc197b0f77'
down_revision: Union[str, None] = '4c8bd011c095'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS pricing_regions")
    op.create_table('pricing_regions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_regions_region_code'), 'pricing_regions', ['region_code'], unique=True)
    op.add_column('jackpots', sa.Column('regional_prices', sa.JSON(), nullable=True))
    op.add_column('subscription_tiers', sa.Column('regional_prices', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_tiers', 'regional_prices')
    op.drop_column('jackpots', 'regional_prices')
    op.drop_index(op.f('ix_pricing_regions_region_code'), table_name='pricing_regions')
    op.drop_table('pricing_regions')
    # ### end Alembic commands ###
