"""Add verification code to users

Revision ID: 1bbd7413fa87
Revises: 765f854ffafb
Create Date: 2026-04-01 23:54:45.413722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bbd7413fa87'
down_revision: Union[str, None] = '765f854ffafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expires_at')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
