"""Add referral points economy fields

Revision ID: 7a24ed5204b9
Revises: 98c7ba1903cb
Create Date: 2026-04-05 01:25:09.469487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7a24ed5204b9'
down_revision: Union[str, None] = '98c7ba1903cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_points', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('referral_discount_active', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('unlocked_tip_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('unlocked_tip_ids')
        batch_op.drop_column('referral_discount_active')
        batch_op.drop_column('referral_points')
    # ### end Alembic commands ###
