"""Add theme and ui flags to campaigns

Revision ID: 98c7ba1903cb
Revises: 04_04_multi_device
Create Date: 2026-04-04 20:14:46.218393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c7ba1903cb'
down_revision: Union[str, None] = '04_04_multi_device'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('theme_color_hex', sa.String(length=7), nullable=True))
    op.add_column('campaigns', sa.Column('use_splash_screen', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('campaigns', sa.Column('use_floating_badge', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('campaigns', sa.Column('use_particle_effects', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('campaigns', sa.Column('use_custom_icons', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'use_custom_icons')
    op.drop_column('campaigns', 'use_particle_effects')
    op.drop_column('campaigns', 'use_floating_badge')
    op.drop_column('campaigns', 'use_splash_screen')
    op.drop_column('campaigns', 'theme_color_hex')
    # ### end Alembic commands ###
