"""auto-generated pre-deploy migration

Revision ID: ec42eea68dec
Revises: b169d18f7409
Create Date: 2026-04-05 23:11:10.380521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec42eea68dec'
down_revision: Union[str, None] = 'b169d18f7409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jackpots', schema=None) as batch_op:
        batch_op.alter_column('variations',
               existing_type=mysql.JSON(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    with op.batch_alter_table('jackpots', schema=None) as batch_op:
        batch_op.alter_column('variations',
               existing_type=mysql.JSON(),
               nullable=True)

    # ### end Alembic commands ###
